processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-196:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "25GQgBra7FTdEgssPMwBVCqG6T2SnCfLWN2bRKSNpXf8",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AJOKd+g1dczh11fHm9Q++W4ovGhUoqwi156UKL1DbhvYh3AeTW9shjXz6eniPzwe6eh/YVKoGn84YDZ5h24f2gJ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "MQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "8xjjJe5QykjAdkbqS5nzuB4ZLE39x16HmN1Nkkj6vZPW"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-7315600",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x2238bdfe6142e4d6b44225847617bf8991a6826fbe0df55a06fd4ce72643387c",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x2238bdfe6142e4d6b44225847617bf8991a6826fbe0df55a06fd4ce72643387c",
                  "digest": "5WqYdMXGLkMggYcsvzHAXxUzjopiGb8Nh7FEqcPB4cs3"
                }
              },
              {
                "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                  "digest": "3nVg6cEtV4aP8eDUAg9PQAKMesk2BG6HBiWpYznSrumW"
                }
              },
              {
                "address": "0xd98a6a6cf2ac69cbef7653803ae64d45cb3f40ab51197842e6d30772bea4bd2c",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xd98a6a6cf2ac69cbef7653803ae64d45cb3f40ab51197842e6d30772bea4bd2c",
                  "digest": "Bg2S7w1fVSGXDMWhQucLsfr3kgfBwHprBDcSVqcwRf8E"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "25GQgBra7FTdEgssPMwBVCqG6T2SnCfLWN2bRKSNpXf8"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 198-216:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 218-218:
Checkpoint created: 2

task 6 'run-graphql'. lines 220-393:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "6L8A96pcufC319FZRLgkXqa7GxPoeD939FRhPvjMn3k5",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "ADnVzBveiG5Q11Xp14PDqyGfsgUzfxPZYVGAzW6Ap5Rq3MjLx0IP6rJiWLMw4GUi9t6a8Od6hN0G9+o7lhb1qQN/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0xd98a6a6cf2ac69cbef7653803ae64d45cb3f40ab51197842e6d30772bea4bd2c",
                    "version": 2,
                    "digest": "Bg2S7w1fVSGXDMWhQucLsfr3kgfBwHprBDcSVqcwRf8E",
                    "object": null
                  }
                },
                {
                  "cursor": "MQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "Mg",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "MQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ],
                    "currentPackage": "0x2238bdfe6142e4d6b44225847617bf8991a6826fbe0df55a06fd4ce72643387c",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "Mg",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": [
              {
                "digest": "8xjjJe5QykjAdkbqS5nzuB4ZLE39x16HmN1Nkkj6vZPW"
              },
              {
                "digest": "25GQgBra7FTdEgssPMwBVCqG6T2SnCfLWN2bRKSNpXf8"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-4993420",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0xac689eb813f469d4533eb206ca125ea039e061671d9c3199a826cb3338a2427d",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xac689eb813f469d4533eb206ca125ea039e061671d9c3199a826cb3338a2427d",
                  "digest": "FYL75mHfyJk91NVEsrcJF9mZ3WEFaQQ95aaDZTCAtYLS"
                }
              },
              {
                "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                  "digest": "DSofwVJH1Xyr6jw8nKfA8dQp6zGBCK3bmsWgtw1gJmiL"
                }
              },
              {
                "address": "0xd98a6a6cf2ac69cbef7653803ae64d45cb3f40ab51197842e6d30772bea4bd2c",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xd98a6a6cf2ac69cbef7653803ae64d45cb3f40ab51197842e6d30772bea4bd2c",
                  "digest": "FVwmDT7haEbmjJweyPmHoPzfJNMd2X6LrKhwjMBedNXB"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "6L8A96pcufC319FZRLgkXqa7GxPoeD939FRhPvjMn3k5"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 395-404:
created: object(7,0), object(7,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 406-406:
Checkpoint created: 3

task 9 'run-graphql'. lines 408-590:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "868aWekNWWueK9f52CBoyXZR6xpQHhoBAWXBvth3hHcu",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AFAN1v61cLmVn9FNXHJVQ11nJKcqdhXEJJGksStr1eB8BzmTlX0OLG/F061KxvJzuqMiRfjEM79dcJd00Rn6nQx/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "MQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "Mg",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "Mw",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "MQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "Mg",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "Mw",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xac689eb813f469d4533eb206ca125ea039e061671d9c3199a826cb3338a2427d",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x2238bdfe6142e4d6b44225847617bf8991a6826fbe0df55a06fd4ce72643387c::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "NA",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "NQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xac689eb813f469d4533eb206ca125ea039e061671d9c3199a826cb3338a2427d",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x2238bdfe6142e4d6b44225847617bf8991a6826fbe0df55a06fd4ce72643387c::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "Ng",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xac689eb813f469d4533eb206ca125ea039e061671d9c3199a826cb3338a2427d",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0x2238bdfe6142e4d6b44225847617bf8991a6826fbe0df55a06fd4ce72643387c::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "Nw",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "OA",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 4,
            "dependencies": [
              {
                "digest": "6L8A96pcufC319FZRLgkXqa7GxPoeD939FRhPvjMn3k5"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-3350680",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x3da5580fbc1c6b5bd7ba49c87b20fafeb00d4120656eea7aa4fc06053a800a5a",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x3da5580fbc1c6b5bd7ba49c87b20fafeb00d4120656eea7aa4fc06053a800a5a",
                  "digest": "HXrRphHVp22vAHyBrQZrkuAbBW3q64e4aQGNMyYzAHTg",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x3da5580fbc1c6b5bd7ba49c87b20fafeb00d4120656eea7aa4fc06053a800a5a",
                        "balance": {
                          "value": "2000"
                        }
                      }
                    }
                  }
                }
              },
              {
                "address": "0x558ed09406ea0bac8b192a71545c8297a0e8b7ed222d9dee4e6cecd436211dbe",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x558ed09406ea0bac8b192a71545c8297a0e8b7ed222d9dee4e6cecd436211dbe",
                  "digest": "8qYJoZH6aEV3u8pE6sa6a91sMFQ5P7nfEsCHK5wk1qAY",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x2238bdfe6142e4d6b44225847617bf8991a6826fbe0df55a06fd4ce72643387c::m::Foo"
                      },
                      "json": {
                        "id": "0x558ed09406ea0bac8b192a71545c8297a0e8b7ed222d9dee4e6cecd436211dbe",
                        "xs": [
                          "42",
                          "43"
                        ]
                      }
                    }
                  }
                }
              },
              {
                "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                  "digest": "AXnofD2esBWWQamrrP4TiYCr2s3hYDFFdzCdqYDqqpYt",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                        "balance": {
                          "value": "299999984338300"
                        }
                      }
                    }
                  }
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "868aWekNWWueK9f52CBoyXZR6xpQHhoBAWXBvth3hHcu"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 10 'programmable'. lines 592-593:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 11 'create-checkpoint'. lines 595-595:
Checkpoint created: 4

task 12 'run-graphql'. lines 597-770:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "4RL57FWyozV84KHFJKa4fcKNsstAitBC32H8AAgji74z",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AHwXZGqew1QjvU4YGw1tsIadKIh5kpSBYy++I3B2Sq6T1nPEh0xBHmmeruxU5wGq43kqTXt5wSUwnNzLbCQ77wp/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 5,
            "dependencies": [
              {
                "digest": "868aWekNWWueK9f52CBoyXZR6xpQHhoBAWXBvth3hHcu"
              }
            ],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "-1009880",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc",
                  "digest": "CddEeunkoBTA2QXhpmYjszvYvUPwehqgDBiTtmBXhhnL"
                }
              }
            ],
            "gasEffects": {
              "gasObject": {
                "address": "0xbe1a4d2c152027d3c73192d66ffa0d70cdcce1059ba437c3a538483b68e461fc"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "4RL57FWyozV84KHFJKa4fcKNsstAitBC32H8AAgji74z"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
