processed 7 tasks

task 1 'publish'. lines 6-26:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 28-29:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'programmable'. lines 31-32:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 4 'programmable'. lines 34-36:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 5 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 6 'run-graphql'. lines 40-85:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xffede2d8012446c2c18058e7ee7076904ef4d3fe6feca247d3a5b01258f6ce9e",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0xffede2d8012446c2c18058e7ee7076904ef4d3fe6feca247d3a5b01258f6ce9e",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": []
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xffede2d8012446c2c18058e7ee7076904ef4d3fe6feca247d3a5b01258f6ce9e",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": []
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xffede2d8012446c2c18058e7ee7076904ef4d3fe6feca247d3a5b01258f6ce9e",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": [
              {
                "__typename": "SharedObjectRead",
                "address": "0x338e9c8e6db91c6fb2298beda240f98d69e414159e2aa892912b02fd685b936b",
                "version": 2,
                "digest": "5T7cUyHsKLGoeKWTagoAeBq1bDuAjdQEPJo5pGJBo7td",
                "object": null
              }
            ]
          }
        }
      ]
    }
  }
}
