processed 8 tasks

task 1 'run-graphql'. lines 8-96:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "BN8e6F7Ax3psbX6x6k2SF9jJtzAuNP9W7mybavm4MymR",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "ImFkZHJlc3Mi",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "ImFzY2lpIg",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "ImJjcyI",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "ImJpdF92ZWN0b3Ii",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "ImRlYnVnIg",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "ImZpeGVkX3BvaW50MzIi",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "Imhhc2gi",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "Im9wdGlvbiI",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "InN0cmluZyI",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "InR5cGVfbmFtZSI",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "InZlY3RvciI",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "MQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "ImFkZHJlc3Mi",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "ImF1dGhlbnRpY2F0b3Jfc3RhdGUi",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "ImJhZyI",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "ImJhbGFuY2Ui",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "ImJjcyI",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "ImJsczEyMzgxIg",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "ImJvcnJvdyI",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "ImNsb2NrIg",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "ImNvaW4i",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "ImRpc3BsYXki",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "ImR5bmFtaWNfZmllbGQi",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "ImR5bmFtaWNfb2JqZWN0X2ZpZWxkIg",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "ImVjZHNhX2sxIg",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "ImVjZHNhX3IxIg",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "ImVjdnJmIg",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "ImVkMjU1MTki",
                            "node": {
                              "name": "ed25519"
                            }
                          },
                          {
                            "cursor": "ImV2ZW50Ig",
                            "node": {
                              "name": "event"
                            }
                          },
                          {
                            "cursor": "Imdyb3RoMTYi",
                            "node": {
                              "name": "groth16"
                            }
                          },
                          {
                            "cursor": "Imhhc2gi",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "ImhleCI",
                            "node": {
                              "name": "hex"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "Mg",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "ImdlbmVzaXMi",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "InN0YWtlX3N1YnNpZHki",
                            "node": {
                              "name": "stake_subsidy"
                            }
                          },
                          {
                            "cursor": "InN0YWtpbmdfcG9vbCI",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "InN0b3JhZ2VfZnVuZCI",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "InN1aV9zeXN0ZW0i",
                            "node": {
                              "name": "sui_system"
                            }
                          },
                          {
                            "cursor": "InN1aV9zeXN0ZW1fc3RhdGVfaW5uZXIi",
                            "node": {
                              "name": "sui_system_state_inner"
                            }
                          },
                          {
                            "cursor": "InZhbGlkYXRvciI",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "InZhbGlkYXRvcl9jYXAi",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "InZhbGlkYXRvcl9zZXQi",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "InZhbGlkYXRvcl93cmFwcGVyIg",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "InZvdGluZ19wb3dlciI",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "Mw",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "NA",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "NQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "Ng",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x92ffbffbaa756adaa72a5cf2a47b28576a7d0252dcaddd986addef987b09178b",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "Nw",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "ImNsb2Ii",
                            "node": {
                              "name": "clob"
                            }
                          },
                          {
                            "cursor": "ImNsb2JfdjIi",
                            "node": {
                              "name": "clob_v2"
                            }
                          },
                          {
                            "cursor": "ImNyaXRiaXQi",
                            "node": {
                              "name": "critbit"
                            }
                          },
                          {
                            "cursor": "ImN1c3RvZGlhbiI",
                            "node": {
                              "name": "custodian"
                            }
                          },
                          {
                            "cursor": "ImN1c3RvZGlhbl92MiI",
                            "node": {
                              "name": "custodian_v2"
                            }
                          },
                          {
                            "cursor": "Im1hdGgi",
                            "node": {
                              "name": "math"
                            }
                          },
                          {
                            "cursor": "Im9yZGVyX3F1ZXJ5Ig",
                            "node": {
                              "name": "order_query"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "OA",
                  "node": {
                    "address": "0x1c9f2f649a497dc8ae6ebdfd1867af5387f6d8e363c20b7073c87d4f7589c569",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x1c9f2f649a497dc8ae6ebdfd1867af5387f6d8e363c20b7073c87d4f7589c569",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "OQ",
                  "node": {
                    "address": "0x3b4e0470ff72c640d57a1a669d4570fee3d0c5232e7204d507162fea5ef31f5d",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                        },
                        "json": {
                          "id": "0x3b4e0470ff72c640d57a1a669d4570fee3d0c5232e7204d507162fea5ef31f5d",
                          "authorizer_validator_address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "MTA",
                  "node": {
                    "address": "0x627521eba29f79986c1069c150bd604fc7c57104b5e28f0c14351ada7f807d16",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                        },
                        "json": {
                          "id": "0x627521eba29f79986c1069c150bd604fc7c57104b5e28f0c14351ada7f807d16",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "epoch": "0",
                            "randomness_round": "0",
                            "random_bytes": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "MTE",
                  "node": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::sui_system_state_inner::SuiSystemStateInner>"
                        },
                        "json": {
                          "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                          "name": "1",
                          "value": {
                            "epoch": "0",
                            "protocol_version": "33",
                            "system_state_version": "1",
                            "validators": {
                              "total_stake": "20000000000000000",
                              "active_validators": [
                                {
                                  "metadata": {
                                    "sui_address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                                    "protocol_pubkey_bytes": [
                                      168,
                                      10,
                                      113,
                                      148,
                                      146,
                                      18,
                                      4,
                                      206,
                                      160,
                                      17,
                                      65,
                                      3,
                                      192,
                                      72,
                                      69,
                                      3,
                                      34,
                                      62,
                                      177,
                                      119,
                                      149,
                                      119,
                                      28,
                                      226,
                                      120,
                                      84,
                                      208,
                                      34,
                                      33,
                                      221,
                                      215,
                                      26,
                                      19,
                                      43,
                                      135,
                                      198,
                                      111,
                                      189,
                                      25,
                                      213,
                                      111,
                                      170,
                                      66,
                                      24,
                                      110,
                                      12,
                                      78,
                                      20,
                                      10,
                                      27,
                                      128,
                                      57,
                                      246,
                                      144,
                                      114,
                                      82,
                                      79,
                                      96,
                                      215,
                                      59,
                                      240,
                                      247,
                                      211,
                                      18,
                                      143,
                                      1,
                                      109,
                                      137,
                                      179,
                                      82,
                                      215,
                                      118,
                                      63,
                                      135,
                                      18,
                                      31,
                                      123,
                                      40,
                                      235,
                                      25,
                                      153,
                                      189,
                                      81,
                                      129,
                                      128,
                                      219,
                                      99,
                                      215,
                                      146,
                                      145,
                                      113,
                                      132,
                                      99,
                                      76,
                                      126,
                                      246
                                    ],
                                    "network_pubkey_bytes": [
                                      222,
                                      193,
                                      56,
                                      253,
                                      223,
                                      140,
                                      108,
                                      228,
                                      161,
                                      246,
                                      151,
                                      172,
                                      42,
                                      190,
                                      219,
                                      243,
                                      212,
                                      210,
                                      59,
                                      152,
                                      5,
                                      6,
                                      236,
                                      134,
                                      82,
                                      53,
                                      90,
                                      224,
                                      105,
                                      93,
                                      152,
                                      85
                                    ],
                                    "worker_pubkey_bytes": [
                                      172,
                                      116,
                                      152,
                                      220,
                                      228,
                                      127,
                                      173,
                                      148,
                                      84,
                                      44,
                                      112,
                                      162,
                                      74,
                                      125,
                                      50,
                                      95,
                                      124,
                                      147,
                                      55,
                                      36,
                                      241,
                                      143,
                                      223,
                                      60,
                                      129,
                                      224,
                                      221,
                                      102,
                                      15,
                                      35,
                                      217,
                                      101
                                    ],
                                    "proof_of_possession": [
                                      128,
                                      156,
                                      67,
                                      33,
                                      58,
                                      1,
                                      39,
                                      117,
                                      201,
                                      238,
                                      255,
                                      186,
                                      75,
                                      160,
                                      126,
                                      112,
                                      202,
                                      232,
                                      153,
                                      37,
                                      253,
                                      202,
                                      71,
                                      140,
                                      94,
                                      117,
                                      125,
                                      17,
                                      181,
                                      101,
                                      235,
                                      149,
                                      12,
                                      103,
                                      135,
                                      36,
                                      124,
                                      64,
                                      40,
                                      191,
                                      203,
                                      204,
                                      20,
                                      212,
                                      46,
                                      230,
                                      32,
                                      74
                                    ],
                                    "name": "validator-0",
                                    "description": "",
                                    "image_url": {
                                      "url": ""
                                    },
                                    "project_url": {
                                      "url": ""
                                    },
                                    "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                    "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                    "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                    "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                    "next_epoch_protocol_pubkey_bytes": null,
                                    "next_epoch_proof_of_possession": null,
                                    "next_epoch_network_pubkey_bytes": null,
                                    "next_epoch_worker_pubkey_bytes": null,
                                    "next_epoch_net_address": null,
                                    "next_epoch_p2p_address": null,
                                    "next_epoch_primary_address": null,
                                    "next_epoch_worker_address": null,
                                    "extra_fields": {
                                      "id": "0x0a2b4566ed9ec3c2c490831ef006d094f4f998e2693426716d43bbeb1fc6123d",
                                      "size": "0"
                                    }
                                  },
                                  "voting_power": "10000",
                                  "operation_cap_id": "0x3b4e0470ff72c640d57a1a669d4570fee3d0c5232e7204d507162fea5ef31f5d",
                                  "gas_price": "1000",
                                  "staking_pool": {
                                    "id": "0x8dd72e681ce54717e36e18727fae17f29b3fa045771b45a794115c5e9d51add8",
                                    "activation_epoch": "0",
                                    "deactivation_epoch": null,
                                    "sui_balance": "20000000000000000",
                                    "rewards_pool": {
                                      "value": "0"
                                    },
                                    "pool_token_balance": "20000000000000000",
                                    "exchange_rates": {
                                      "id": "0xf2a3c25f54bf16416e9b32b70454e358f825962e6f9b7f1a25da97e826da83ef",
                                      "size": "1"
                                    },
                                    "pending_stake": "0",
                                    "pending_total_sui_withdraw": "0",
                                    "pending_pool_token_withdraw": "0",
                                    "extra_fields": {
                                      "id": "0x0306e130483815a835034a7a42f4bd3a4a1afed498069692a0add53a0b72d176",
                                      "size": "0"
                                    }
                                  },
                                  "commission_rate": "200",
                                  "next_epoch_stake": "20000000000000000",
                                  "next_epoch_gas_price": "1000",
                                  "next_epoch_commission_rate": "200",
                                  "extra_fields": {
                                    "id": "0xdb5e7251aceb8dcc745b3eb63b88e790a0e2b9a85ed680e88f2e65d860fdad4d",
                                    "size": "0"
                                  }
                                }
                              ],
                              "pending_active_validators": {
                                "contents": {
                                  "id": "0x1aa00f2d315c667b1886cbfb6cefb771d71fd91f5c26a928969cff721a3136e7",
                                  "size": "0"
                                }
                              },
                              "pending_removals": [],
                              "staking_pool_mappings": {
                                "id": "0x419e06a1be6b84aaa5808dcc3a8ee34d816210a935729afea233efa89850f535",
                                "size": "1"
                              },
                              "inactive_validators": {
                                "id": "0x374762e4fead83ee896baa662e91a1b39d4d992e1452fbbce01d6970ce2628fd",
                                "size": "0"
                              },
                              "validator_candidates": {
                                "id": "0x12862c37c351a73ed6bee05e554004c0cb8a6c4a82aed5ed1e56f307c4b26745",
                                "size": "0"
                              },
                              "at_risk_validators": {
                                "contents": []
                              },
                              "extra_fields": {
                                "id": "0x2464f19208932cf9a7567371e0cb54290351ed4d2f670e4f6ca780c14c17fe88",
                                "size": "0"
                              }
                            },
                            "storage_fund": {
                              "total_object_storage_rebates": {
                                "value": "0"
                              },
                              "non_refundable_balance": {
                                "value": "0"
                              }
                            },
                            "parameters": {
                              "epoch_duration_ms": "86400000",
                              "stake_subsidy_start_epoch": "0",
                              "max_validator_count": "150",
                              "min_validator_joining_stake": "30000000000000000",
                              "validator_low_stake_threshold": "20000000000000000",
                              "validator_very_low_stake_threshold": "15000000000000000",
                              "validator_low_stake_grace_period": "7",
                              "extra_fields": {
                                "id": "0x4de281bc336a44f4364d7fc24cae25314b0d6f04b6d360204df6fedaafe922fa",
                                "size": "0"
                              }
                            },
                            "reference_gas_price": "1000",
                            "validator_report_records": {
                              "contents": []
                            },
                            "stake_subsidy": {
                              "balance": {
                                "value": "9949700000000000000"
                              },
                              "distribution_counter": "0",
                              "current_distribution_amount": "1000000000000000",
                              "stake_subsidy_period_length": "10",
                              "stake_subsidy_decrease_rate": 1000,
                              "extra_fields": {
                                "id": "0x32320ba4c7ef42ce26162d6d9a1c21f8ca0b0eca975f25669a318942239390fb",
                                "size": "0"
                              }
                            },
                            "safe_mode": false,
                            "safe_mode_storage_rewards": {
                              "value": "0"
                            },
                            "safe_mode_computation_rewards": {
                              "value": "0"
                            },
                            "safe_mode_storage_rebates": "0",
                            "safe_mode_non_refundable_storage_fee": "0",
                            "epoch_start_timestamp_ms": "0",
                            "extra_fields": {
                              "id": "0xba0af1cabebb289fea94dc6e5af3a0aef6b777d8d6c84e6abf0d84b71ff3a7fa",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "MTI",
                  "node": {
                    "address": "0x994319b3f33717ee4a128b9579c0b0b2db589532a846a9387ba41f4316913f3d",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                        },
                        "json": {
                          "id": "0x994319b3f33717ee4a128b9579c0b0b2db589532a846a9387ba41f4316913f3d",
                          "name": "0x8dd72e681ce54717e36e18727fae17f29b3fa045771b45a794115c5e9d51add8",
                          "value": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "MTM",
                  "node": {
                    "address": "0xa02fba8640ea605b83ae19183fd8a0d8da9d3769e99ba6ce89bff12927a07ec7",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xa02fba8640ea605b83ae19183fd8a0d8da9d3769e99ba6ce89bff12927a07ec7",
                          "decimals": 9,
                          "name": "Sui",
                          "symbol": "SUI",
                          "description": "",
                          "icon_url": null
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "MTQ",
                  "node": {
                    "address": "0xb19998090d8f30deb1d5ecca69dc0b6ed6f04dbe24a9da1c8c583c024c2ed7a9",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                        },
                        "json": {
                          "id": "0xb19998090d8f30deb1d5ecca69dc0b6ed6f04dbe24a9da1c8c583c024c2ed7a9",
                          "name": "0",
                          "value": {
                            "sui_amount": "0",
                            "pool_token_amount": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "MTU",
                  "node": {
                    "address": "0xb2e230d51d57f2990f1611c420de44afe98cee764e5ed44e1428174f66aed008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xb2e230d51d57f2990f1611c420de44afe98cee764e5ed44e1428174f66aed008",
                          "balance": {
                            "value": "30000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "MTY",
                  "node": {
                    "address": "0xc0e412e1a27c917b766c68c1a7eee184081fb56fa81b719bafdff695f030ebc1",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                        },
                        "json": {
                          "id": "0xc0e412e1a27c917b766c68c1a7eee184081fb56fa81b719bafdff695f030ebc1",
                          "pool_id": "0x8dd72e681ce54717e36e18727fae17f29b3fa045771b45a794115c5e9d51add8",
                          "stake_activation_epoch": "0",
                          "principal": {
                            "value": "20000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "MTc",
                  "node": {
                    "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorStateInner>"
                        },
                        "json": {
                          "id": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "active_jwks": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": [],
            "balanceChanges": [
              {
                "owner": {
                  "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                },
                "amount": "30000000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              },
              {
                "owner": {
                  "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "300000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "digest": "GxFeoZZvcAywxCPoupQRiaew7m5dXFByWgRBhBSXE1YA"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "digest": "4z1SkKVp3RgoqeWgUtZAUaK2oXpzXmtNLHpv5nVW7Hyq"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "digest": "9wftA6gRKSeDiWDpsj7MG1ZMNEvhRRfQKhVGaXoHHdGx"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "7dpjzvB4tY9NkzuGAwnde4itwHPv9LUSq1APzonMqpAS"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "9xsFYEo9ejGMTkDDoWjLgUnsN6RJPnw3hp6BhEfx8GR1"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "digest": "4tb6uDps47hpvoHdVXsgQxnfAXXKbZTJQFrRJS8ty1hG"
                }
              },
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "digest": "8Wsqw4keWVMs2nYb8yVLCFHHDnCGdb7HxpbZA7QYyK8y"
                }
              },
              {
                "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "digest": "7dMkKJm1bDzzJNMgNzwTvmBvsRiQmBQg6JmjHAyn3FBk"
                }
              },
              {
                "address": "0x1c9f2f649a497dc8ae6ebdfd1867af5387f6d8e363c20b7073c87d4f7589c569",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x1c9f2f649a497dc8ae6ebdfd1867af5387f6d8e363c20b7073c87d4f7589c569",
                  "digest": "6bW5bxJdg8ESomM3XWgEherF2YT5NdXmSZhDb1JnnfB9"
                }
              },
              {
                "address": "0x3b4e0470ff72c640d57a1a669d4570fee3d0c5232e7204d507162fea5ef31f5d",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x3b4e0470ff72c640d57a1a669d4570fee3d0c5232e7204d507162fea5ef31f5d",
                  "digest": "HCST5aRFp1EoZcJYuro8EsKSSfCQRLt5H3n5WWihRcip"
                }
              },
              {
                "address": "0x627521eba29f79986c1069c150bd604fc7c57104b5e28f0c14351ada7f807d16",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x627521eba29f79986c1069c150bd604fc7c57104b5e28f0c14351ada7f807d16",
                  "digest": "CHTuhgoNfici9ka48SdjBggw6u3KTWfkmD31m99JHyAg"
                }
              },
              {
                "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "digest": "7eiFDnMs2Qt1FwiFBKodu8akioNaoBHoMY6LPt17wBJW"
                }
              },
              {
                "address": "0x994319b3f33717ee4a128b9579c0b0b2db589532a846a9387ba41f4316913f3d",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x994319b3f33717ee4a128b9579c0b0b2db589532a846a9387ba41f4316913f3d",
                  "digest": "T6ubauhVrN1oWGksEitHxKG398CnSS1WWrWuBKGx5cB"
                }
              },
              {
                "address": "0xa02fba8640ea605b83ae19183fd8a0d8da9d3769e99ba6ce89bff12927a07ec7",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xa02fba8640ea605b83ae19183fd8a0d8da9d3769e99ba6ce89bff12927a07ec7",
                  "digest": "14eoucf7YbKyeTk9LJEMAJtXZHZDH7k1NqNwSBLfe28R"
                }
              },
              {
                "address": "0xb19998090d8f30deb1d5ecca69dc0b6ed6f04dbe24a9da1c8c583c024c2ed7a9",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xb19998090d8f30deb1d5ecca69dc0b6ed6f04dbe24a9da1c8c583c024c2ed7a9",
                  "digest": "7vabGTVsKY6kHDwHEEBQEfmuUFiqpZCSgrk7VQ7Uzr3Q"
                }
              },
              {
                "address": "0xb2e230d51d57f2990f1611c420de44afe98cee764e5ed44e1428174f66aed008",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xb2e230d51d57f2990f1611c420de44afe98cee764e5ed44e1428174f66aed008",
                  "digest": "wQ1CuVh2GcXb1QssvtQ4PjGwbK9BmLMd7A5BjfMpBBa"
                }
              },
              {
                "address": "0xc0e412e1a27c917b766c68c1a7eee184081fb56fa81b719bafdff695f030ebc1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xc0e412e1a27c917b766c68c1a7eee184081fb56fa81b719bafdff695f030ebc1",
                  "digest": "6ob7ebKt9erYuMpiF75kBtm9wRHjfRkiEKbpq7pTH7ip"
                }
              },
              {
                "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "digest": "8sfsPtaViJA3Ay417DH8bzEPheHyD4BJ4764zTNWzRFR"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "BN8e6F7Ax3psbX6x6k2SF9jJtzAuNP9W7mybavm4MymR"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3 'create-checkpoint'. lines 100-100:
Checkpoint created: 1

task 4 'run-graphql'. lines 102-171:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "BN8e6F7Ax3psbX6x6k2SF9jJtzAuNP9W7mybavm4MymR"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "28w3Mp2x4vt94bq4TejrbLcfMsMaevDyPz6h98sgcnw4"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6 'advance-epoch'. lines 175-175:
Epoch advanced: 0

task 7 'run-graphql'. lines 177-258:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "Hcm4VRREF7BMTHLMy25ZFce4b2x6zhdPRi1MoMBLwpaE",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": {
                      "epochId": 1
                    },
                    "protocolVersion": 33,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "BN8e6F7Ax3psbX6x6k2SF9jJtzAuNP9W7mybavm4MymR"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "J1nhWGfCYDessGpN996RAgJUyWkn28VAWsWWPTg5oWkN"
                }
              },
              {
                "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "digest": "AvFhG3soP9kJvuLxPfkqYm9uHV5wcsVBE8qnSSirhwum"
                }
              },
              {
                "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": false,
                "idDeleted": true,
                "outputState": null
              },
              {
                "address": "0xd7cb4f9a08e0546ae754e1d5698be933ad7d4aa726b5b1fdd8711d90a3ce7d73",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "address": "0xd7cb4f9a08e0546ae754e1d5698be933ad7d4aa726b5b1fdd8711d90a3ce7d73",
                  "digest": "5Cnz9LknGd7zV7onhMzqvvNypAhzAjRAcy1qjcVsN9k3"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "Hcm4VRREF7BMTHLMy25ZFce4b2x6zhdPRi1MoMBLwpaE"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
