processed 26 tasks

init:
validator_0: object(0,0)

task 1 'publish'. lines 6-28:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 30-30:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 32-32:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'view-object'. lines 34-34:
Owner: Account Address ( validator_0 )
Version: 1
Contents: sui_system::staking_pool::StakedSui {id: sui::object::UID {id: sui::object::ID {bytes: fake(0,0)}}, pool_id: sui::object::ID {bytes: _}, stake_activation_epoch: 0u64, principal: sui::balance::Balance<sui::sui::SUI> {value: 20000000000000000u64}}

task 5 'view-object'. lines 36-36:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 6 'view-object'. lines 38-38:
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(3,0)}}, value: 0u64}

task 7 'create-checkpoint'. lines 40-40:
Checkpoint created: 4

task 8 'view-checkpoint'. lines 42-42:
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, storage_cost: 10176400, storage_rebate: 1956240, non_refundable_storage_fee: 19760 }}

task 9 'advance-epoch'. lines 45-45:
Epoch advanced: 5

task 10 'view-checkpoint'. lines 47-47:
CheckpointSummary { epoch: 5, seq: 10, content_digest: Ep5cSPjqtENoUXSZYcN5mnJ64NyRKQ2f9EwwZYZuJpuf,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11 'run-graphql'. lines 49-55:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12 'create-checkpoint'. lines 56-56:
Checkpoint created: 11

task 13 'view-checkpoint'. lines 58-58:
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14 'run-graphql'. lines 60-66:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15 'run-graphql'. lines 68-74:
Headers: {
    "content-type": "application/json",
    "content-length": "137",
    "x-sui-rpc-version": "0.1.0",
}
Service version: 0.1.0
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "nodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "query_payload": 41
    }
  }
}

task 16 'view-checkpoint'. lines 76-76:
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17 'advance-epoch'. lines 78-81:
Epoch advanced: 6

task 18 'run-graphql'. lines 83-96:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "node": {
              "address": "0x85a192df6fc2bbb8328e2269a2bb15de74164d97145b9c5868f622a3c358346f",
              "digest": "5BKgihFfNPvzQMRJLaUyH85gqrJfYRsMByubpqqvov6M",
              "kind": "OWNED"
            }
          }
        ]
      }
    }
  }
}

task 19 'run-graphql'. lines 98-145:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": []
      }
    },
    "second": {
      "objectConnection": {
        "edges": [
          {
            "node": {
              "address": "0x85a192df6fc2bbb8328e2269a2bb15de74164d97145b9c5868f622a3c358346f",
              "digest": "5BKgihFfNPvzQMRJLaUyH85gqrJfYRsMByubpqqvov6M",
              "kind": "OWNED"
            }
          }
        ]
      }
    },
    "val_objs": {
      "objectConnection": {
        "edges": [
          {
            "node": {
              "address": "0x0126c80c7e1c524b819add1fde41d1bf473ab28e2f7ae684833ddba90ae0bf99",
              "digest": "GTQAU1yYq66Fuur6HF4gf5biSG9LEfSo9LRz1yJNGD7H",
              "kind": "OWNED",
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          },
          {
            "node": {
              "address": "0x1b8fb982d0d01176b87b8cc059f5bb34f14a4bdf552a219ade97c275fee5c057",
              "digest": "7BpQoWqZ5AneSdpD5p1FB5cmSqqtks6FDLQBXm8FzfAM",
              "kind": "OWNED",
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          },
          {
            "node": {
              "address": "0x511fd9ce0b6943a3968d0d5cc377322cd0118433f65dcb51e9d1727d771047f0",
              "digest": "3ks9ZHj3pi44yeHuwmxKnZdCLnqPrY3i5cxq4UQ4HzGt",
              "kind": "OWNED",
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          },
          {
            "node": {
              "address": "0xa9f9ef4044ceb168ab3b75b31ce10004760a86334379456d5bf5eff8ca0334a2",
              "digest": "NwjKqb4xwncrTXW8MTa9Ei6qhGJnnyAgtYF6fMxtRZ9",
              "kind": "OWNED",
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          },
          {
            "node": {
              "address": "0xb76f66089742b9f1811c47f2ffcf004d8846d2657d83b8421c8b78bdea8637ea",
              "digest": "7hZBzaxPdPKe4FegK1AbMfd9Gjkk3awcirRenEA9smfh",
              "kind": "OWNED",
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          },
          {
            "node": {
              "address": "0xe3a7e37536594b5b73e73f8f5b42c276ac44ed7a1d55b850129b1025b08ece63",
              "digest": "DvYkxa3aipF8p3eUXQEeD9EWMWdp8AcsK7aJhZjrUVau",
              "kind": "OWNED",
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
      }
    }
  }
}

task 20 'view-graphql-variables'. lines 148-149:
Name: A
Type: SuiAddress!
Value: "0x42"

Name: A_opt
Type: SuiAddress
Value: "0x42"

Name: Test
Type: SuiAddress!
Value: "0xad797ef8af5cc9460a23b4a587939d38b4e8b1a0d82b0d724bea2249ab74efcf"

Name: Test_opt
Type: SuiAddress
Value: "0xad797ef8af5cc9460a23b4a587939d38b4e8b1a0d82b0d724bea2249ab74efcf"

Name: deepbook
Type: SuiAddress!
Value: "0xdee9"

Name: deepbook_opt
Type: SuiAddress
Value: "0xdee9"

Name: obj_0_0
Type: SuiAddress!
Value: "0x0126c80c7e1c524b819add1fde41d1bf473ab28e2f7ae684833ddba90ae0bf99"

Name: obj_0_0_opt
Type: SuiAddress
Value: "0x0126c80c7e1c524b819add1fde41d1bf473ab28e2f7ae684833ddba90ae0bf99"

Name: obj_0_1
Type: SuiAddress!
Value: "0x89afa33961838d84e04687b8a17460fce9720d22409c4f6215734fe7ef98e1a9"

Name: obj_0_1_opt
Type: SuiAddress
Value: "0x89afa33961838d84e04687b8a17460fce9720d22409c4f6215734fe7ef98e1a9"

Name: obj_1_0
Type: SuiAddress!
Value: "0xad797ef8af5cc9460a23b4a587939d38b4e8b1a0d82b0d724bea2249ab74efcf"

Name: obj_1_0_opt
Type: SuiAddress
Value: "0xad797ef8af5cc9460a23b4a587939d38b4e8b1a0d82b0d724bea2249ab74efcf"

Name: obj_2_0
Type: SuiAddress!
Value: "0x85a192df6fc2bbb8328e2269a2bb15de74164d97145b9c5868f622a3c358346f"

Name: obj_2_0_opt
Type: SuiAddress
Value: "0x85a192df6fc2bbb8328e2269a2bb15de74164d97145b9c5868f622a3c358346f"

Name: obj_3_0
Type: SuiAddress!
Value: "0xe3a7e37536594b5b73e73f8f5b42c276ac44ed7a1d55b850129b1025b08ece63"

Name: obj_3_0_opt
Type: SuiAddress
Value: "0xe3a7e37536594b5b73e73f8f5b42c276ac44ed7a1d55b850129b1025b08ece63"

Name: std
Type: SuiAddress!
Value: "0x1"

Name: std_opt
Type: SuiAddress
Value: "0x1"

Name: sui
Type: SuiAddress!
Value: "0x2"

Name: sui_opt
Type: SuiAddress
Value: "0x2"

Name: sui_system
Type: SuiAddress!
Value: "0x3"

Name: sui_system_opt
Type: SuiAddress
Value: "0x3"

Name: validator_0
Type: SuiAddress!
Value: "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"

Name: validator_0_opt
Type: SuiAddress
Value: "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"

task 21 'run-graphql'. lines 152-166:
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": [
          {
            "address": {
              "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
            }
          }
        ]
      }
    },
    "address": {
      "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
    }
  }
}

task 22 'run-graphql'. lines 168-174:
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 23 'run'. lines 176-176:
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 24 'run'. lines 178-178:
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 25 'run'. lines 180-180:
created: object(25,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880
