processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 44-46:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 48-48:
Checkpoint created: 1

task 4 'run-graphql'. lines 50-69:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "effects": {
            "objectChanges": [
              {
                "outputState": {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0xc4a41c018f95ac37b6213998aa5e8f067cef10278b683ba695fb1047f01cf149::m::Foo"
                      },
                      "data": {
                        "Struct": [
                          {
                            "name": "id",
                            "value": {
                              "UID": [
                                16,
                                10,
                                249,
                                178,
                                208,
                                85,
                                37,
                                214,
                                245,
                                30,
                                40,
                                77,
                                133,
                                23,
                                240,
                                208,
                                80,
                                137,
                                52,
                                24,
                                239,
                                82,
                                191,
                                190,
                                236,
                                121,
                                255,
                                4,
                                90,
                                120,
                                204,
                                199
                              ]
                            }
                          },
                          {
                            "name": "f0",
                            "value": {
                              "ID": [
                                16,
                                10,
                                249,
                                178,
                                208,
                                85,
                                37,
                                214,
                                245,
                                30,
                                40,
                                77,
                                133,
                                23,
                                240,
                                208,
                                80,
                                137,
                                52,
                                24,
                                239,
                                82,
                                191,
                                190,
                                236,
                                121,
                                255,
                                4,
                                90,
                                120,
                                204,
                                199
                              ]
                            }
                          },
                          {
                            "name": "f1",
                            "value": {
                              "Bool": true
                            }
                          },
                          {
                            "name": "f2",
                            "value": {
                              "Number": "42"
                            }
                          },
                          {
                            "name": "f3",
                            "value": {
                              "Number": "43"
                            }
                          },
                          {
                            "name": "f4",
                            "value": {
                              "String": "hello"
                            }
                          },
                          {
                            "name": "f5",
                            "value": {
                              "String": "world"
                            }
                          },
                          {
                            "name": "f6",
                            "value": {
                              "Vector": [
                                {
                                  "Address": [
                                    16,
                                    10,
                                    249,
                                    178,
                                    208,
                                    85,
                                    37,
                                    214,
                                    245,
                                    30,
                                    40,
                                    77,
                                    133,
                                    23,
                                    240,
                                    208,
                                    80,
                                    137,
                                    52,
                                    24,
                                    239,
                                    82,
                                    191,
                                    190,
                                    236,
                                    121,
                                    255,
                                    4,
                                    90,
                                    120,
                                    204,
                                    199
                                  ]
                                }
                              ]
                            }
                          },
                          {
                            "name": "f7",
                            "value": {
                              "Option": {
                                "Number": "44"
                              }
                            }
                          }
                        ]
                      },
                      "json": {
                        "id": "0x100af9b2d05525d6f51e284d8517f0d050893418ef52bfbeec79ff045a78ccc7",
                        "f0": "0x100af9b2d05525d6f51e284d8517f0d050893418ef52bfbeec79ff045a78ccc7",
                        "f1": true,
                        "f2": 42,
                        "f3": "43",
                        "f4": "hello",
                        "f5": "world",
                        "f6": [
                          "0x100af9b2d05525d6f51e284d8517f0d050893418ef52bfbeec79ff045a78ccc7"
                        ],
                        "f7": 44
                      }
                    }
                  }
                }
              },
              {
                "outputState": {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "data": {
                        "Struct": [
                          {
                            "name": "id",
                            "value": {
                              "UID": [
                                63,
                                16,
                                187,
                                190,
                                233,
                                13,
                                167,
                                83,
                                130,
                                143,
                                182,
                                127,
                                252,
                                154,
                                41,
                                43,
                                95,
                                215,
                                212,
                                1,
                                58,
                                233,
                                228,
                                112,
                                144,
                                185,
                                105,
                                168,
                                5,
                                34,
                                82,
                                212
                              ]
                            }
                          },
                          {
                            "name": "balance",
                            "value": {
                              "Struct": [
                                {
                                  "name": "value",
                                  "value": {
                                    "Number": "299999988444520"
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      },
                      "json": {
                        "id": "0x3f10bbbee90da753828fb67ffc9a292b5fd7d4013ae9e47090b969a8052252d4",
                        "balance": {
                          "value": "299999988444520"
                        }
                      }
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
