processed 14 tasks

task 1 'publish'. lines 6-23:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 25-25:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 27-27:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 29-29:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 31-31:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 33-33:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 8 'run-graphql'. lines 37-47:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x3b54dbb2507cf962160145cf00287fe2698dd7ae1d57d1adb99b499718a71cfe"
          },
          {
            "cursor": "0x7e5b2eef4b171391b79c114132e2fb650ac876722447f94a41e06186c9aa434d"
          },
          {
            "cursor": "0x8182198d235265e9beae9f03bec54a473cd1c7786e69f95f7f1e356550e4844c"
          },
          {
            "cursor": "0xcffe670fb526c2bb69fdbf5df08a99359d8417d0ebb14db29c43e3e9b4a47996"
          },
          {
            "cursor": "0xf236b2d0d2d43dc1371cd7b0a059f5faba658327baf68004644a094d516dcad5"
          }
        ]
      }
    }
  }
}

task 9 'run-graphql'. lines 49-59:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x3b54dbb2507cf962160145cf00287fe2698dd7ae1d57d1adb99b499718a71cfe"
          },
          {
            "cursor": "0x7e5b2eef4b171391b79c114132e2fb650ac876722447f94a41e06186c9aa434d"
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 61-73:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xf236b2d0d2d43dc1371cd7b0a059f5faba658327baf68004644a094d516dcad5"
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 75-85:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": []
      }
    }
  }
}

task 12 'run-graphql'. lines 87-97:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": []
      }
    }
  }
}

task 13 'run-graphql'. lines 99-108:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xcffe670fb526c2bb69fdbf5df08a99359d8417d0ebb14db29c43e3e9b4a47996"
          },
          {
            "cursor": "0xf236b2d0d2d43dc1371cd7b0a059f5faba658327baf68004644a094d516dcad5"
          }
        ]
      }
    }
  }
}
